apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    name:
    namespace:
    labels:


spec:
  containers:
  - name:
    image:
    ports:
    - containerPort:
    resources: {}

status: {}